from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

#server
GIF_LOCAL_SERVER_PORT = 666
GENERATOR_SERVER_PORT = 777

#gif
MAX_GIF_GENERATIONS_AT_TIME = 1
GIF_MAKER_SERVER_URI = f"http://localhost:{GIF_LOCAL_SERVER_PORT}"
ANIM_STEP = 0.03

#png
DEFAULT_PNG_WIDTH = 552 * 2
DEFAULT_PNG_HEIGHT = 736 * 2
DEFAULT_TRAIT_WIDTH = 380 * 2
DEFAULT_TRAIT_HEIGHT = 600 * 2